/*
 * EXTI_config.h
 *
 *  Created on: Sep 6, 2024
 *      Author: DELL
 */

#ifndef MCAL_EXTI_EXTI_CONFIG_H_
#define MCAL_EXTI_EXTI_CONFIG_H_

/*
 * EXTI_RISING_EDGE
 * EXTI_FALLING_EDGE
 * EXTI_ANY_CHANGE
 * EXTI_LOW_LEVEL
 */
#define EXTI_INT_0_SENSE       EXTI_RISING_EDGE

/*
 * EXTI_RISING_EDGE
 * EXTI_FALLING_EDGE
 * EXTI_ANY_CHANGE
 * EXTI_LOW_LEVEL
 */
#define EXTI_INT_1_SENSE       EXTI_RISING_EDGE

/*
 * EXTI_RISING_EDGE
 * EXTI_FALLING_EDGE
 */
#define EXTI_INT_1_SENSE       EXTI_RISING_EDGE

#endif /* MCAL_EXTI_EXTI_CONFIG_H_ */
