/*
 * TIMER0_config.h
 *
 *  Created on: 20 Sep 2024
 *      Author: AMIT
 */

#ifndef MCAL_TIMER0_TIMER0_CONFIG_H_
#define MCAL_TIMER0_TIMER0_CONFIG_H_

/*
 * TIMER0_NORMAL_MODE
 * TIMER0_CTC_MODE
 * TIMER0_FAST_PWM_MODE
 * TIMER0_PC_PWM_MODE
 */


#define TIMER0_MODE       TIMER0_CTC_MODE



/*
 * TIMER0_NO_CLK_SRC
 * TIMER0_NO_PRESCALER
 * TIMER0_NO_DIV_8
 * TIMER0_NO_DIV_64
 * TIMER0_NO_DIV_256
 * TIMER0_NO_DIV_1024
 * TIMER0_EXT_FALLING
 * TIMER0_EXT_RISING
 */

#define TIMER0_PRESCALER      TIMER0_NO_PRESCALER


#if  TIMER0_MODE    ==   TIMER0_CTC_MODE
/*
 * TIMER0_OC0_DISCONNECTED
 * TIMER0_OC0_TOGGLE_ON_CM
 * TIMER0_OC0_CLR_ON_CM
 * TIMER0_OC0_SET_ON_CM
 */
#define TIMER0_OC0_MODE    TIMER0_OC0_TOGGLE_ON_CM
#endif

#if  TIMER0_MODE    ==   TIMER0_FAST_PWM_MODE
/*
 * TIMER0_DISconnected
 * TIMER0_NONINVERTING
 * TIMER0_INVERTING
 */
#define TIMER0_OC0_MODE    TIMER0_NONINVERTING
#endif




#define TIMER0_OCR0_INITIAL_VAL     249         //OCR VALUE
#define TIMER0_TCNT0_INITIAL_VAL    0              //PRELOAD INTIAL VALUE

#endif /* MCAL_TIMER0_TIMER0_CONFIG_H_ */
